version:  '3'
services:
  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - db-laravel-01-data:/var/lib/mysql
    ports:
    - 3306:3306
  web:
    build: ./docker
    image: gfreezz/laravel-dev
    volumes:
    - /home/ubuntu/projects/laravel-01:/var/www/html/
    environment:
      PHP_IDE_CONFIG: serverName=web
    ports:
    - 80:80
    depends_on:
      - db
volumes:
  db-laravel-01-data: