version:  '3'
services:
  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - db-laravel-01-data:/var/lib/mysql
    ports:
    - 3307:3306
  web:
    build: ./docker
    image: gfreezz/laravel-dev
    volumes:
    - ../laravel-01:/var/www/html/
    - web-laravel-01-var-data:/var/www/html/var
    - web-laravel-01-vendor-data:/var/www/html/vendor
    environment:
      PHP_IDE_CONFIG: serverName=web
    ports:
    - 80:80
volumes:
  db-laravel-01-data:
  web-laravel-01-var-data:
  web-laravel-01-vendor-data: